---
################################################
## Packages Presence
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'presence'

    ################################################
    ## Sensor
    ################################################

    sensor.bedar_status:
      <<: *customize
      entity_picture: /local/images/people/bedar.jpeg

    sensor.sunshine_status:
      <<: *customize
      entity_picture: /local/images/people/sunshine.jpg

    ################################################
    ## Input Select
    ################################################

    input_select.bedar_status_dropdown:
      <<: *customize
      hidden: true

    input_select.sunshine_status_dropdown:
      <<: *customize
      hidden: true

    ################################################
    ## Automation
    ################################################

    automation.markeer_persoon_als_lang_weg:
      <<: *customize
      hidden: true

    automation.markeer_persoon_als_net_aangekomen:
      <<: *customize
      hidden: true

    automation.markeer_persoon_als_net_vertrokken:
      <<: *customize
      hidden: true

    automation.markeer_persoon_als_thuis:
      <<: *customize
      hidden: true

    automation.markeer_persoon_als_weg:
      <<: *customize
      hidden: true

################################################
## Input Select
################################################
input_select:
  # Aanwezigheids optie Bedar
  bedar_status_dropdown:
    name: Bedar
    options:
      - Thuis
      - Net Aangekomen
      - Net Vertrokken
      - Weg
      - Lang Weg

  # Aanwezigheids optie Sunshine
  sunshine_status_dropdown:
    name: Sunshine
    options:
      - Thuis
      - Net Aangekomen
      - Net Vertrokken
      - Weg
      - Lang Weg

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      bedar_status:
        value_template: '{{ states.input_select.bedar_status_dropdown.state }}'
        friendly_name: 'Bedar'
      sunshine_status:
        value_template: '{{ states.input_select.sunshine_status_dropdown.state }}'
        friendly_name: 'Sunshine'

################################################
## Group
################################################
group:
  personen_status:
    name: Personen Status
    entities:
      - sensor.bedar_status
      - sensor.sunshine_status

################################################
## Automation
################################################
automation:
  # Net Aangekomen
  - alias: Presence - Markeer persoon als net aangekomen
    initial_state: true
    trigger:
      # Bedar
      - platform: state
        entity_id: binary_sensor.bedar_thuis
        from: 'off'
        to: 'on'
      # Sunshine
      - platform: state
        entity_id: binary_sensor.sunshine_thuis
        from: 'off'
        to: 'on'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'binary_sensor.bedar_thuis' %}
              input_select.bedar_status_dropdown
            {% else %}
              input_select.sunshine_status_dropdown
            {% endif %}
          option: >
            {% if trigger.entity_id == 'binary_sensor.bedar_thuis' %}
              {% if states.input_select.bedar_status_dropdown.state == 'Net Vertrokken' %}
                Thuis
              {% else %}
                Net Aangekomen
              {% endif %}
            {% else %}
              {% if states.input_select.sunshine_status_dropdown.state == 'Net Vertrokken' %}
                Thuis
              {% else %}
                Net Aangekomen
              {% endif %}
            {% endif %}

  # Thuis
  - alias: Presence - Markeer persoon als thuis
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.bedar_status_dropdown
        to: 'Net Aangekomen'
        for: "00:10:00"
      - platform: state
        entity_id: input_select.sunshine_status_dropdown
        to: 'Net Aangekomen'
        for: "00:10:00"
      - platform: state
        entity_id: input_select.bedar_status_dropdown
        from: 'Net Vertrokken'
        to: 'Net Aangekomen'
      - platform: state
        entity_id: input_select.sunshine_status_dropdown
        from: 'Net Vertrokken'
        to: 'Net Aangekomen'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.bedar_status_dropdown' %}
              input_select.bedar_status_dropdown
            {% else %}
              input_select.sunshine_status_dropdown
            {% endif %}
          option: Thuis

  # Net Vertrokken
  - alias: Presence - Markeer persoon als net vertrokken
    initial_state: true
    trigger:
      # Bedar
      - platform: state
        entity_id: binary_sensor.bedar_thuis
        from: 'on'
        to: 'off'
      # Sunshine
      - platform: state
        entity_id: binary_sensor.sunshine_thuis
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'binary_sensor.bedar_thuis' %}
              input_select.bedar_status_dropdown
            {% else %}
              input_select.sunshine_status_dropdown
            {% endif %}
          option: Net Vertrokken

  # Weg
  - alias: Presence - Markeer persoon als weg
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.bedar_status_dropdown
        to: 'Net Vertrokken'
        for: "00:10:00"
      - platform: state
        entity_id: input_select.sunshine_status_dropdown
        to: 'Net Vertrokken'
        for: "00:10:00"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.bedar_status_dropdown' %}
              input_select.bedar_status_dropdown
            {% else %}
              input_select.sunshine_status_dropdown
            {% endif %}
          option: Weg

  # Lang weg
  - alias: Presence - Markeer persoon als lang weg
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.bedar_status_dropdown
        to: 'Weg'
        for: "24:00:00"
      - platform: state
        entity_id: input_select.sunshine_status_dropdown
        to: 'Weg'
        for: "24:00:00"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.bedar_status_dropdown' %}
              input_select.bedar_status_dropdown
            {% else %}
              input_select.sunshine_status_dropdown
            {% endif %}
          option: Lang Weg
