---
################################################
## Packages - System Info
################################################

homeassistant:
  customize_glob:
    weblink.*:
      icon: mdi:web

  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "system"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Sensor
    ################################################

    sensor.processor_use:
      <<: *customize
      friendly_name: Processorgebruik

    sensor.memory_use_percent:
      <<: *customize
      friendly_name: Geheugengebruik

    sensor.disk_free:
      <<: *customize
      friendly_name: Beschikbare opslag

    sensor.disk_use_percent:
      <<: *customize
      friendly_name: Gebruikte opslag

    sensor.current_version:
      <<: *customize
      friendly_name: Home Assistant geinstalleerde versie

    sensor.python_version:
      <<: *customize
      friendly_name: Python geinstalleerde versie

    sensor.last_boot:
      <<: *customize
      friendly_name: Laatste (re)boot Intel NUC

    sensor.myip:
      <<: *customize
      friendly_name: Publiek IP-adres
      icon: mdi:network

    sensor.local_ip:
      <<: *customize
      friendly_name: Intern IP-adres
      icon: mdi:network

################################################
## Binary Sensor
################################################

template:
  - binary_sensor:
      - name: cpu_high
        state: "{{ states.sensor.processor_use.state | float > 80 }}"

  - binary_sensor:
      - name: cpu_hot
        state: "{{ states.sensor.cpu_temperature.state | float > 65 }}"

################################################
## Sensor
################################################

sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: disk_use_percent
        arg: /
      - type: disk_free
        arg: /
      - type: last_boot
      - type: swap_use_percent
      - type: ipv4_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0

  ##### Latest installed python3 version
  - platform: command_line
    name: Python Version
    command: python3 --version
    scan_interval: 86400

  ##### MariaDB Size
  - platform: sql
    db_url: !secret recorder_db_url
    queries:
      - name: mariadb_size
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: "value"
        unit_of_measurement: MB

  ##### Restart time
  - platform: command_line
    name: HA Restart Time
    command: "/bin/cat /config/home-assistant.log | /bin/grep 'Home Assistant initialized in' | /usr/bin/awk '{print $10}' | /bin/sed 's/[^0-9.]//g'"
    scan_interval: 60
    unit_of_measurement: "sec"

################################################
## Input boolean
################################################

input_boolean:
  maintenance_mode:
    name: Maintenance Mode
    icon: mdi:auto-fix
