---
## UnRAID Version Sensor URLs
### Stable URL: https://s3.amazonaws.com/dnld.lime-technology.com/stable/unRAIDServer.plg
### Beta URL: https://s3.amazonaws.com/dnld.lime-technology.com/next/unRAIDServer.plg
sensor:
  # API sensors

  ## UnRaid Array Started Bar-Card  > 3.1.0
  - platform: template
    sensors:
      unraid_array_status:
        friendly_name: UnRAID Array Status
        value_template: >
          {{state_attr("binary_sensor.tower_server", "arrayStatus")}}
      unraid_array_status_numerical:
        friendly_name: UnRAID Array Status
        value_template: >
          {% if is_state("sensor.unraid_array_status", "Started") %}
            1
          {% else %}
            0
          {% endif %}
      ## UnRaid Array Protection Bar-Card  > 3.1.0
      unraid_array_protection:
        friendly_name: UnRAID Array Protection
        value_template: >
          {{state_attr("binary_sensor.tower_server", "arrayProtection")}}
      unraid_array_protection_numerical:
        friendly_name: UnRAID Array Protection
        value_template: >
          {% if is_state("sensor.unraid_array_protection", "Parity is valid.") %}
            1
          {% else %}
            0
          {% endif %}
      ## UnRaid Array Usage
      unraid_array_space:
        friendly_name: UnRAID Array Space
        value_template: >
          {% set state = state_attr("switch.tower_array", "diskSpace") %} 
          {{ Offline if state == None else state | regex_findall_index(".*\((\d+.?\d+) %\)") | float }}
        unit_of_measurement: "%"

      ## UnRaid Version
      unraid_version:
        friendly_name: UnRAID Version
        value_template: >
          {{state_attr("binary_sensor.tower_server", "version")}}

      unraid_vms_active:
        friendly_name: Unraid VM's active
        value_template: |
          {{states.sensor 
          |selectattr('entity_id', 'search', '_vm_')
          |map(attribute='state')
          |select('eq','started')
          |list|count }}

  ## HDD SNMP Temperatures

  - platform: snmp
    name: "UnRAID PARITY Temperature"
    host: !secret unraid_address
    port: 161
    community: public
    version: 2c
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.1
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: "°C"

  - platform: snmp
    name: "UnRAID DISK1 Temperature"
    host: !secret unraid_address
    port: 161
    community: public
    version: 2c
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.1
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: "°C"

  - platform: snmp
    name: "UnRAID DISK2 Temperature"
    host: !secret unraid_address
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.2
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: "°C"

  - platform: snmp
    name: "UnRAID DISK3 Temperature"
    host: !secret unraid_address
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.3
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: "°C"

  - platform: snmp
    name: "UnRAID DISK4 Temperature"
    host: !secret unraid_address
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.4
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: "°C"

  - platform: snmp
    name: "UnRAID DISK5 Temperature"
    host: !secret unraid_address
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.5
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: "°C"

  - platform: snmp
    name: "UnRAID DISK6 Temperature"
    host: !secret unraid_address
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.6
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: "°C"

  ## SNMP LAN Upload

  - platform: snmp
    name: "UnRAID LAN0 Upload"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.17
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
  - platform: snmp
    name: "UnRAID LAN1 Upload"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.13
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
  - platform: snmp
    name: "UnRAID LAN2 Upload"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.14
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
  - platform: snmp
    name: "UnRAID LAN3 Upload"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.15
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
  - platform: snmp
    name: "UnRAID LAN4 Upload"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.16
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
  ## SNMP LAN Download
  - platform: snmp
    name: "UnRAID LAN0 Download"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.17
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
  - platform: snmp
    name: "UnRAID LAN1 Download"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.13
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
  - platform: snmp
    name: "UnRAID LAN2 Download"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.14
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
  - platform: snmp
    name: "UnRAID LAN3 Download"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.15
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
  - platform: snmp
    name: "UnRAID LAN4 Download"
    host: !secret unraid_address
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.16
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}
