- id: '1648497011565'
  alias: Living room control
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.livingroom_control_action
      helper_last_controller_event: input_text.livingroom_control_last_event
      action_button_left_short:
      - device_id: 8b934ce942c664aaa63c71f3c6624d37
        domain: light
        entity_id: light.livingroom_lights
        type: brightness_decrease
      action_button_right_short:
      - device_id: 8b934ce942c664aaa63c71f3c6624d37
        domain: light
        entity_id: light.livingroom_lights
        type: brightness_increase
      action_button_right_long:
      - device_id: 8b934ce942c664aaa63c71f3c6624d37
        domain: light
        entity_id: light.livingroom_lights
        type: brightness_increase
      action_button_left_long:
      - device_id: 8b934ce942c664aaa63c71f3c6624d37
        domain: light
        entity_id: light.livingroom_lights
        type: brightness_decrease
      action_button_up_long: []
      action_button_center_short:
      - type: toggle
        device_id: 8b934ce942c664aaa63c71f3c6624d37
        entity_id: light.livingroom_lights
        domain: light
- id: '1648499066298'
  alias: Toilet light
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion_occupancy
    from: 'off'
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: 3178e4e6eeb1c21d063009899e5a48e6
    entity_id: light.bathroom_light_1
    domain: light
    brightness_pct: 50
  - delay:
      hours: 0
      minutes: 4
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 3178e4e6eeb1c21d063009899e5a48e6
    entity_id: light.bathroom_light_1
    domain: light
  mode: single
