- id: '1648499066298'
  alias: Toilet light
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion_occupancy
    from: 'off'
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: 3178e4e6eeb1c21d063009899e5a48e6
    entity_id: light.bathroom_light_1
    domain: light
    brightness_pct: 50
  - delay:
      hours: 0
      minutes: 4
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 3178e4e6eeb1c21d063009899e5a48e6
    entity_id: light.bathroom_light_1
    domain: light
  mode: single
