- id: '1648725339746'
  alias: Toilet light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.bathroom_motion_occupancy
      light_target:
        device_id: 3178e4e6eeb1c21d063009899e5a48e6
      no_motion_wait: 300
