---
- alias: "Notificatie: Deurbel audio"
  id: doorbell_audio
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur_doorbell
      from: "off"
      to: "on"
  action:
    - service: media_player.volume_set
      data:
        entity_id:
          - media_player.kitchen_speaker
          - media_player.bedroom_display
          - media_player.livingroom_speaker
        volume_level: 0.8
    - service: media_player.play_media
      data:
        entity_id:
          - media_player.kitchen_speaker
          - media_player.bedroom_display
          - media_player.livingroom_speaker
        media_content_id: !secret http_audio_deurbel
        media_content_type: music
