---
- alias: "Startup Notification"
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    - service: notify.pushover
      data:
        title: "🎉 Terug opgestart! 🎉"
        message: "🎉 Homeassistant is terug opgestart! 🎉"
