alias: "Deurbel: Bericht op display"
id: doorbell_display
trigger:
  - platform: state
    entity_id: binary_sensor.frontdoor_motion
    to: person
    attribute: event_object
  - platform: template
    value_template: "{{ as_timestamp(now()) - as_timestamp(state_attr('binary_sensor.frontdoor_motion', 'last_tripped_time')) < 10 }}"
  - platform: state
    entity_id: binary_sensor.frontdoor_doorbell
    from: "off"
    to: "on"
  - platform: template
    value_template: "{{ as_timestamp(now()) - as_timestamp(state_attr('binary_sensor.frontdoor_doorbell', 'last_tripped_time')) < 10 }}"
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.frontdoor_doorbell
            state: "on"
          - condition: template
            value_template: "{{ as_timestamp(now()) - as_timestamp(state_attr('binary_sensor.frontdoor_doorbell', 'last_tripped_time')) < 10 }}"
          - condition: state
            entity_id: group.device_status
            state: "home"
          # - condition: state
          #   entity_id: binary_sensor.frontdoor
          #   state: "off"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.frontdoor_doorbell_text
              message: "MOMENTJE..."
              duration: 6
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "12:00:00"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.frontdoor_doorbell_text
              message: "GOEDEMORGEN"
      #                duration: 5
      - conditions:
          - condition: time
            after: "12:00:00"
            before: "17:30:00"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.frontdoor_doorbell_text
              message: "GOEDEMIDDAG"
      - conditions:
          - condition: time
            after: "17:30:00"
            before: "23:59:00"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.frontdoor_doorbell_text
              message: "GOEDENAVOND"
      - conditions:
          - condition: time
            after: "00:00:00"
            before: "06:00:00"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.frontdoor_doorbell_text
              message: "GOEDENACHT"
    default:
      - service: unifiprotect.set_doorbell_message
        data:
          entity_id: select.frontdoor_doorbell_text
          message: "HALLO :)"