---
alias: "Notificatie: Deurbel snapshot"
id: doorbell_snapshot
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.voordeur_doorbell
    from: "off"
    to: "on"
# condition:
# ### dit voorkomt het klapperen
#   condition: template
#   value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.notificatie_deurbel_snapshot.attributes.last_triggered | default(0)) | int > 10)}}'
action:
  - service: camera.snapshot
    data:
      entity_id: camera.voordeur
      filename: "/config/www/images/snapshots/cam_voordeur.jpg"
  - service: notify.mobile_app_oneplus
    data:
      title: "Deurbel"
      message: "Er is aangebeld!"
      data:
        attachment:
          url: !secret http_camera_voordeur
          content-type: jpeg
          hide-thumbnail: false
        actions:
          - action: URI
            title: View in HA
            uri: dwains-dashboard/more_page_addon_camera_s
          - action: URI
            title: View in Protect
            uri: "app://com.ubnt.unifi.protect"
  - service: notify.mobile_app_samsung
    data:
      title: "Deurbel"
      message: "Er is aangebeld!"
      data:
        attachment:
          url: !secret http_camera_voordeur
          content-type: jpeg
          hide-thumbnail: false
        actions:
          - action: URI
            title: Bekijk in HA
            uri: dwains-dashboard/more_page_addon_camera_s
  - service: notify.pushover
    data:
      title: "🔔 Deurbel"
      message: "Er is aangebeld!"
      data:
        sound: pushover
        attachment: "/config/www/images/snapshots/cam_voordeur.jpg"
  - service: notify.lg_webos_tv_up75006lf
    data:
      title: "🔔  Deurbel"
      message: "Er is aangebeld!"
      data:
        fontsize: small
        position: top-right
        duration: 10
        interrupt: true
        file:
          path: "/config/www/images/snapshots/cam_voordeur.jpg"