---
id: "1425859982062"
alias: House - Sunshine is home
initial_state: on
trigger:
  - platform: zone
    entity_id: person.sunshine
    zone: zone.home
    event: enter
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ not is_state('person.bedar', 'home') }}"
  - condition: time
    after: "09:00:00"
    before: "23:00:00"
action:
  - service: tts.google_say
    data:
      entity_id: media_player.home_mini
      message: "Welcome home my queen"
      language: "en"
